### ISSUE TITLE
handler to restart iptables doesn't use iptables-persistent service

### ISSUE THREAD

**Issue by adespain** [grupoversia/cis-ubuntu-ansible#2]
I noticed that this role installs iptables-persistent but in the handler it never uses it, it just manually loads the iptables rules with a shell command.  Is there a reason why?  I think in 16.04 it is called netfilter-persistent...

**Comment by rubenrodr-versia** [comment]
iptables rules are non maintained across reboots, the handler only loads the rules, so we use iptables-persistent according to:
https://help.ubuntu.com/community/IptablesHowTo
